// packages/abilities/src/store/constants.ts
var STORE_NAME = "core/abilities";
var ABILITY_NAME_PATTERN = /^[a-z0-9-]+(?:\/[a-z0-9-]+){1,3}$/;
var CATEGORY_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
var REGISTER_ABILITY = "REGISTER_ABILITY";
var UNREGISTER_ABILITY = "UNREGISTER_ABILITY";
var REGISTER_ABILITY_CATEGORY = "REGISTER_ABILITY_CATEGORY";
var UNREGISTER_ABILITY_CATEGORY = "UNREGISTER_ABILITY_CATEGORY";
export {
  ABILITY_NAME_PATTERN,
  CATEGORY_SLUG_PATTERN,
  REGISTER_ABILITY,
  REGISTER_ABILITY_CATEGORY,
  STORE_NAME,
  UNREGISTER_ABILITY,
  UNREGISTER_ABILITY_CATEGORY
};
//# sourceMappingURL=constants.mjs.map
