server {
    listen 80;
    listen [::]:80;
    server_name wp.hperkins.com;

    root /home/dev/wp-hperkins-com;
    index index.php index.html;

    client_max_body_size 64m;

    access_log /var/log/nginx/wp-hperkins-com.access.log;
    error_log /var/log/nginx/wp-hperkins-com.error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        default_type "text/plain";
        try_files $uri =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ /\. {
        deny all;
    }

    location = /xmlrpc.php {
        deny all;
    }
}
